on: 
  push:
    branches:
      - master
name: ğŸš€ Deploy project
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2

      - name: ğŸ¥¨ Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: ğŸ”¨ Build Project
        run: |
          npm install
          npm run build

      - name: ğŸ’¾ Upload files
        uses: actions/upload-artifact@v3
        with:
          name: poetic-praxis-artifacts
          path: dist

      - name: ğŸ“„ Display structure of downloaded files
        run: ls -R
        working-directory: dist
